# fly.toml app configuration file generated for causal-quartets on 2024-11-11T18:56:13-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'causal-quartets'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
