[project]
name = "causal-quartets"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "marimo>=0.9.17",
    "matplotlib>=3.9.2",
    "y0>=0.2.11",
]
